= Castlevania, Barbarianna Viking Edition
// completar mails
Blanco Gabriel <gabrielblanco2399@gmail.com>; Carro_Avila Emmanuel <CarroavilaEmm@gmail.com>; Ledesma Tomas <tomasld13@gmail.com>
v1.0, {docdate}
:toc:
:toc-title:Contenidos
:numbered:

== Introduccion 

  Ayuda a nuestra heroina Barbariana, a atravezar las turbulencias del tiempo, y escalar las torres mas peligrosas,
   mientras peleas con dinosaurios mutantes y persigues al doctor Gero, que ha violado las leyes del tiempo y 
   se ha apoderado de la Commodore 128kb.


== En juego:

=== Vikinga: Barbarianna será nuestro personaje principal, ella realizará la mayor cantidad de tareas.
  Barbarianna puede saltar, moverse, disparar rayos e ir subiendo de piso en piso hasta conseguir la Commodore
  Por eso hemos concentrado en vikinga una gran cantidad de atributos que nos permita desarrollar esas acciones.

 * Esta clase contará con el método Dibujar:
    - Para dibujarse, la vikinga solo necesitará 2 parametros (x,y) que la posicionarán en la ubicación definida
    para el inicio del juego o el raspawn.
    - Según la actividad que esté realizando barbariana, se utilizará una imagen distinta de extension .GIF.
    Se implementaron imagenes para: saltar, correr, y estar quieta. Todas las imagenes se editaron desde
    la pagina "http:// www.gifgifs.com", esto permitió ajustar el sentido de las imagenes, derecha o izquierda,
    segun la acción que realiza nuestro personaje. Esta pagina se utilizó en la edición de todas las imagenes de este juego,
    al igual que Photoshop.
 
 * Movimientos:
    - los metodos moverHaciaDerecha y moverHaciaIzquierda, estan delimitados por el entorno, y guardan
    una variable llamada _direccion_, que será la que usaremos para ajustar tanto las imagenes de barbariana, como
    el sentido del rayo y el escudo. 

 * Cambio de piso:
    - Segun donde este parada, Barbarianna podrá subir de piso, o caer al piso anterior.
    Para permitir el movimiento entre dichos pisos, se le ha otorgado a barbarianna una banderaDeSalto y una BanderaDeCaida.
    Estas funciones nos devolveran true o false segun donde esté parada la vikinga. De activarse la banderaDeSalto,
    nuestro personaje tendrá permido saltar hasta el piso siguiente, y si se activa la banderaDeCaida la vikinga caerá
    hasta chocarse con el piso anterior.
    
  * Vikinga creadora de objetos:
    - La clase disparar hace un nuevo Rayo, dando origen a otro objeto del juego con sus propios atributos y comportamientos.
    lo mismo ocurre con Bloquear, que crea un escudo para proteger a barbarianna de los lasers enemigos.
    Ambos objetos se originan en la clase barbarianna, porque efectivamente surgen de ella.
      public Rayo disparar() {
      public Escudo bloquear() {  
    - Tanto el rayo como el escudo utilizarán como parámetros la posicion _x_ e _y_ de barbariana y la _direccion_
    en la que se está moviendo.

  * Peligros para Barbarianna:
    - Se han trabajado 2 choques peligrosos para nuestro personaje en los métodos _ChoqueRaptor_ y _chocasteUnLaser_.
    ambos choques son capaces de acabar con una de las vidas de Barbarianna. Por eso en estas funciones incluimos en el 
    argumento al raptor y al laser respectivamente, para poder asi calcular la posición de ambos y detectar la colisión
    con nuestra vikinga.

  * Ganar:
    - _recuperasteCommodore_ es la función que permite a Barbarianna saber si ha llegado a la posicion de la Commodore 128kb
     evaluando una colisión con el objeto. De esta manera habremos logrado el objetivo de nuestra heroina.

=== Velocirraptor: Nuestros recurrentes y veloces enemigos irán descendiendo ferózmente por los pisos del castillo. Una alteración
 en la linea temporal hizo que estas temibles criaturas arrojen rayos de sus bocas, y solo podrán ser detenidos por los 
 poderes de nuestra heroina.
  
  * Movimiento: Los raptors solo pueden moverse de izquierda a derecha, iran rebotando al llegar a los límites del entorno y caerán
  al llegar al hueco de cada piso. Otra vez, en esta clase, la variable _direccion_ determinará la imagen del raptor y la
  direccion en la que disparará los lasers.

  * Ataque: Los raptors irán disparando rayos a medida que van descendiendo. estos rayos pueden quitar vidas a la vikinga, y se
  originarán en la posicion del velocirraptor, respetando el direccionamiento. De esta manera el Laser pasa a ser otro objeto del
  juego.

  * Muerte: Aunque estas criaturas sean temibles, un simple rayo de nuestra heronia puede destruirlos.
  En la funcion _chocasteUnRayo_ se evalúa la posicion del raptor y se verifica un posible impacto con el poder de Barbarianna.
  De darse la colisión, tanto el raptor como el rayo seran puestos en _null_, es decir, serán destruidos.


=== Escudo y Rayo: Estos objetos son creados dentro de la clase Vikinga. Ambos utilizan la posicion y direccionamiento de la
vikinga para dibujarse.
 
  * Utilidad: A estas dos clases se le evaluará la posición constantemente para verificar si han colisiónado con otro objeto.
  por ese motivo no tienen otro comportamiento mas que dibujarse.

=== Laser: Son una amenaza constante, pero a diferencia del velociraptor, pueden ser bloqueados por el escudo magico de Barbarianna.
 Este objeto se origina dentro de Velocirraptor, y desaparece cuando llega al límite del entorno o cuando el escudo los destruye.

=== Pisos: Esta clase, si bien se pensó como un objeto estático, durante el desarrollo se ha convirtido en una clase de referencia.
 Con el correr de los días se otorgó al piso la funcion de evaluar el contacto con otro objeto. Esto permitió obtener las posiciones 
 de caida de los raptors y la vikinga, como asi tambien la posición de ascenso, para sortear los distintos pisos.

=== commodore

=== Juego




==Implementacion 

Una seccion de implementaci´on donde se incluya el c´odigo fuente correctamente formateado y comentado, si corresponde.


==Conclusiones Algunas reflexiones acerca del desarrollo del trabajo realizado, y de los resultados obtenidos. Pueden incluirse lecciones aprendidas durante el desarrollo del trabajo.
